# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voley', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='datosJornada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
