# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voley', '0002_auto_20160625_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombreIdentificativo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
